/**
 * LuxeCart Premium E-commerce Dashboard
 * Copyright (c) 2025 desheekart
 * Developer: Raviranjan Kumar
 * License: Single Use License - CodeCanyon
 */

// Advanced source code protection
export const sourceProtection = {
    // Disable right-click
    disableRightClick: () => {
        document.addEventListener('contextmenu', (e) => {
            e.preventDefault();
            alert('© 2025 desheekart - All Rights Reserved');
        });
    },

    // Disable keyboard shortcuts
    disableKeyboardShortcuts: () => {
        document.addEventListener('keydown', (e) => {
            // Prevent Ctrl+Shift+I (Dev Tools)
            if (e.ctrlKey && e.shiftKey && e.keyCode === 73) {
                e.preventDefault();
            }
            // Prevent Ctrl+U (View Source)
            if (e.ctrlKey && e.keyCode === 85) {
                e.preventDefault();
            }
            // Prevent Ctrl+Shift+C (Dev Tools)
            if (e.ctrlKey && e.shiftKey && e.keyCode === 67) {
                e.preventDefault();
            }
        });
    },

    // Add console warning
    addConsoleWarning: () => {
        const style = 'color: red; font-size: 24px; font-weight: bold; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);';
        console.log('%c⚠️ Warning!', style);
        console.log('%cThis is a protected version of LuxeCart Premium', 'font-size: 16px; color: #444;');
        console.log('%c© 2025 desheekart - Developed by Raviranjan Kumar', 'font-size: 14px; color: #666;');
    },

    // Add hidden watermark in DOM
    addHiddenWatermark: () => {
        const watermarks = [];
        for (let i = 0; i < 10; i++) {
            const watermark = document.createElement('div');
            watermark.style.cssText = `
                position: fixed;
                pointer-events: none;
                user-select: none;
                opacity: 0.03;
                z-index: 9999;
                font-family: monospace;
                color: #000;
                transform: rotate(-45deg);
            `;
            watermark.innerHTML = `desheekart © 2025<br>Developed by Raviranjan Kumar`;
            
            // Random position
            watermark.style.top = Math.random() * 100 + '%';
            watermark.style.left = Math.random() * 100 + '%';
            
            document.body.appendChild(watermark);
            watermarks.push(watermark);
        }
    },

    // Add metadata to exported files
    addExportMetadata: (data, type = 'json') => {
        const metadata = {
            creator: 'desheekart',
            developer: 'Raviranjan Kumar',
            timestamp: new Date().toISOString(),
            license: 'Single Use License - CodeCanyon'
        };

        if (type === 'json') {
            return {
                ...data,
                _metadata: metadata
            };
        }

        if (type === 'csv') {
            return `# Generated by LuxeCart Premium\n# © 2025 desheekart\n# Developer: Raviranjan Kumar\n${data}`;
        }

        return data;
    },

    // Initialize all protections
    init: () => {
        sourceProtection.disableRightClick();
        sourceProtection.disableKeyboardShortcuts();
        sourceProtection.addConsoleWarning();
        sourceProtection.addHiddenWatermark();

        // Add protection notice to window object
        Object.defineProperty(window, '__luxecart_protected', {
            value: true,
            writable: false,
            configurable: false
        });

        // Periodic check for tampering
        setInterval(() => {
            if (!window.__luxecart_protected) {
                location.reload();
            }
        }, 1000);
    }
};

// Initialize protection
if (typeof window !== 'undefined') {
    sourceProtection.init();
}
